# Generated by Django 3.1.2 on 2020-10-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationopportunity',
            name='d_org',
            field=models.CharField(max_length=75),
        ),
    ]
