# Generated by Django 3.1.2 on 2020-10-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0002_auto_20201022_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_variable', models.CharField(max_length=75)),
                ('number_variable', models.CharField(max_length=75)),
            ],
        ),
    ]
