# Generated by Django 3.1.2 on 2020-10-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0003_namenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeropportunity',
            name='start_datetime',
        ),
    ]
