# Generated by Django 3.1.2 on 2020-10-22 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0004_remove_volunteeropportunity_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
