# Generated by Django 3.1.1 on 2020-10-30 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_1_37', '0005_volunteeropportunity_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationopportunity',
            name='d_donator',
            field=models.ManyToManyField(to='project_1_37.Profile'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='volunteers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
