# Generated by Django 3.1.1 on 2020-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0009_volunteeropportunity_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='hours',
            field=models.TimeField(),
        ),
    ]
