# Generated by Django 3.1.1 on 2020-11-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0010_auto_20201113_1200'),
        ('project_1_37', '0009_auto_20201105_0249'),
    ]

    operations = [
    ]
