# Generated by Django 3.1.1 on 2020-11-15 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0012_donationtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
