# Generated by Django 3.1.1 on 2020-11-15 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_1_37', '0013_donationtransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationopportunity',
            name='d_donator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
