# Generated by Django 3.1.1 on 2020-11-20 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_37', '0015_auto_20201115_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='hours',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
